Typeform/ci-standard-checks

- .github/workflows/ci-standard-checks.yml
:warning: As a code owner, you are expected to review and merge (the bot will not merge by itself).
This PR adds the Typeform's CI Standard check to the PR that will do:
- a JIRA link check
- the Secret scan check
This PR will help you with gain 2 badges:
- Secrets Scan check (mandatory for Q2)
- CI Standard Checks (informative for Q2, mandatory for Q3)
This means that if you already have a a secrets detection workflow / part of travis in your repo, you can safely delete it without affecting the badge ratio. 
This PR should have deleted the 'secrets-scan.yml' from your repo. 
Note: if you have the secrets-detection workflow in pending after deletion, it means that it's a mandatory check in a protected branch. 
Please go to Settings -> Branches -> Edit Protected Branch -> Uncheck …
> chore: [SETI-1159] :construction_worker: add ci standard workflow

- scripts/secrets-scan/run.sh
This `gitleaks-config` PR [changed the Dockerfile entrypoint](https://github.com/Typeform/gitleaks-config/pull/33/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R11) of `gitleaks-config`. Now the `CMD` has the default call which is to calculate the `gitleaks` configuration file and print it to `STDOUT`.
Therefore, we can remove the redundant call.
> chore(SP-1216): updating gitleaks-config call

- package.json
- src/checks/piiDetection.test.ts
- src/checks/piiDetection.ts
- src/infrastructure/__mocks__/github.ts
- src/infrastructure/github.ts
- yarn.lock
On the Codecov incident the security team discovered that `.csv` files with Personal Identifiable Information (PII or "personal data") were uploaded to some repos. Uploading legit personal data to repos is not allowed as it conflicts with GDPR.
This PR adds a new check that will scan every new `.csv` file uploaded to a repo. The check does the following:
1. Scan the whole file using Regexp's that look for US phone numbers, emails, US social security numbers, and credit card numbers. This can be extended in a future.
2. If any of those Regexp's match more than `CsvDetectionThreshold` lines of the file, currently 70%, it is considered that the file contains PII.
3. If any file contains PII the check prints out the results and a Notion page URL with more info and it returns `false`.
As with …
> feat(SP-1221): PII detection check

- README.md
- src/checks/piiDetection.test.ts
- src/checks/piiDetection.ts
From the repo's `README.md`:
> To make your check pass, return a value. To make it fail, throw an Error. The error message will be caught and printed to the action output.
> fix(SP-1221): throwing error when check does not pass

- scripts/secrets-scan/run.sh
This PR updates the tool `gitleaks` used in the secrets detection check to its latest major version.
`gitleaks` API and exception file for every repo (`.gitleaks.toml`) is broken with this new version. So, the migration plan I have in mind is the following:
1. Merge this into `ci-standard-checks@v1-beta`
2. Test secrets detection in repos that use `ci-standard-checks@v1-beta`
3. Submit PRs to all repos that have a `.gitleaks.toml` file and use `ci-standard-checks@v1`. The PR will update `.gitleaks.toml` to make it compatible with `gitleaks` version 8 and also make the repos use `ci-standard-checks@v1-beta`
4. Once all PRs from previous step are merged, promote `ci-standard-checks@v1-beta` to `ci-standard-checks@v1` and submit PRs to the same repos to make them use `ci-standard-checks@v1` …
> feat(SP-1744): update to gitleaks v8

- .github/workflows/test-and-release-beta.yml
Previous token didn't have enough permissions.
> ci(NOJIRA-1): using github token with correct scope

- scripts/secrets-scan/run.sh
This PR fixes an issue with secrets detection. The bash commands `head` and `tail` were not being passed the `-n1` argument, therefore making `gitleaks` go kinda crazy and scan the entire git tree.
> fix(SP-1914): fix commits being used in gitleaks scan

- .gitleaks.toml
This PR generated by SourceGraph updates the `.gitleaks.toml` file format to be compatible with gitleaks v8.
This repo is using `ci-standard-checks@v1-beta` which [has been updated to use the latest gitleaks v8](https://github.com/Typeform/ci-standard-checks/pull/119).
[_Created by Sourcegraph batch change `david.salvador/update-gitleaks-config-to-v8-in-v1beta`._](https://sourcegraph.tools.typeform.tf/users/david.salvador/batch-changes/update-gitleaks-config-to-v8-in-v1beta)
> chore(SP-1745): using new gitleaks v8 configuration file format

- .gitleaks.toml
This PR generated by SourceGraph updates the `.gitleaks.toml` file format to be compatible with gitleaks v8.
This repo is using `ci-standard-checks@v1-beta` which [has been updated to use the latest gitleaks v8](https://github.com/Typeform/ci-standard-checks/pull/119).
[_Created by Sourcegraph batch change `david.salvador/update-gitleaks-config-all-repos`._](https://sourcegraph.tools.typeform.tf/users/david.salvador/batch-changes/update-gitleaks-config-all-repos)
> chore(SP-1747): using new gitleaks v8 configuration file format

- scripts/secrets-scan/run.sh
As per [gitleaks documentation](https://github.com/zricethezav/gitleaks):
>When running detect on a git repository, gitleaks will parse the output of a git log -p command (you can see how this executed [here](https://github.com/zricethezav/gitleaks/blob/7240e16769b92d2a1b137c17d6bf9d55a8562899/git/git.go#L17-L25)). git log -p[ generates patches](https://git-scm.com/docs/git-log#_generating_patch_text_with_p) which gitleaks will use to detect secrets.
And, [because of an issue with false positives](https://typeform.slack.com/archives/CCWDN8ASJ/p1660895849830629?thread_ts=1659448611.368089&cid=CCWDN8ASJ), we discovered that when running `git log -p $base..$head` the `$base` commit is not included in the output because the interval is not inclusive on the left operand (a `git` feature).
This …
> fix(SP-1936): base commit not being secret scanned

- scripts/validate-openapi/.redocly.yaml
- scripts/validate-openapi/run.sh
Update the redocly package name (old one is deprecated) and add a new config file (soon to be required) to match the api-docs repository config
⚠️ It has been tested in forms-api and toltec
- Change package name
- Add configuration file
> fix(openapi): change redocly package name and add a config file

- action.yml
We are getting a warning from `ci-standard-checks` about the node version:
> [ci-standard-checks](https://github.com/Typeform/public-main-site/actions/runs/3280777332/jobs/5401976950)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, Typeform/ci-standard-checks, actions/checkout
You can see the annotation warning here: https://github.com/Typeform/public-main-site/actions/runs/3280777332
This PR is setting a new version for node.
> chore(WEB-5102): set node version to 16

- README.md
- scripts/validate-openapi/run.sh
In some cases, such as serverless-based services exposing their API as a
set of functions, each with its own hostname, more than one
`openapi.yaml` file may be needed to document a service's full API.
The adds supports for multiple `openapi.yaml`
files to the openAPI validation script, validating, linting and bundling all of them.
> [SS-1865] multiple openapi files support

- scripts/validate-openapi/run.sh
Fix `find` syntax in openAPI validation
A bug was introduced by a previous commit: `find`'s `-depth` argument
causes a depth-first search to be performed, instead of limiting search
depth as intended. This commit hence uses `-maxdepth` instead.
Tested by @jordiroig-tf via [this job](https://github.com/Typeform/auth-api/actions/runs/3830507410).
> Fix `find` syntax in openAPI validation

- src/conditions/belongsToTypeformOrg.test.ts
- src/conditions/belongsToTypeformOrg.ts
Certain repositories are stored in a different Github organization named `typeform-security`. Checks like Secrets Detection and PII Detection are very important to have there too.
> feat(SP-2174): adding typeform-security org

- package.json
- yarn.lock
This PR fixes an issue with Node.js 18 and `@vercel/ncc`. The issue is fixed by upgrading the package. The issue is
> In Node.js v17, the Node.js developers closed a security hole in the SSL provider. This fix was a breaking change that corresponded with similar breaking changes in the SSL packages in NPM. When you attempt to use SSL in Node.js v17 or later without also upgrading those SSL packages in your package.json, then you will see this error.
[Source](https://stackoverflow.com/a/73027407)
> fix(NOJIRA-1): fix digital envelope error

- scripts/secrets-scan/run.sh
This PR bumps the `gitleaks` version. This is needed to use the `extend` feature which reduces complexity of the rules file, more info in [SP-2214](https://typeform.atlassian.net/browse/SP-2214).
[SP-2214]: https://typeform.atlassian.net/browse/SP-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(SP-2214): upgrade gitleaks version

- scripts/secrets-scan/run.sh
This PR fixes a variable scoping error in the secrets detection script that made the private or public runner check always return public. Thus, making Docker rate limit us again.
> fix(SP-2457): private or public runner check

- CODEOWNERS
As api-docs is owned by engineering community, this check should be, too.
> chore(CODEOWNERS): same owners for api-docs and ci-standard-check

- scripts/validate-openapi/run.sh
This allows support for openapi specs that use circular references (such as forms-api's Fields property).
`redocly` does not have the ability to control circular references when bundling the spec in JSON format.
`api-docs`'s CI using a [transformation](https://github.com/Typeform/api-docs/pull/801) to resolve this problem.
However, repos that reference the published components, that are generated by api-docs, will still be faced with the circular reference (e.g. https://typeform.design/api-docs/schema/Field.yaml).
`api-docs`'s CI is solely responsible for generating the "official" `openapi.json` spec bundle. It downloads all the `openapi.yaml` files from the other API repos and bundles them with the common models defined in `api-docs`.
The `validate-openapi` step of the …
> feat(TU-26042): switch redocly bundle to yaml format
